/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SpSideDrawer {
    'open': () => Promise<void>;
    'opened': boolean;
    'title': string;
  }
  interface SpStockPrice {}
  interface SpTooltipToggle {
    'text': string;
  }
}

declare global {


  interface HTMLSpSideDrawerElement extends Components.SpSideDrawer, HTMLStencilElement {}
  var HTMLSpSideDrawerElement: {
    prototype: HTMLSpSideDrawerElement;
    new (): HTMLSpSideDrawerElement;
  };

  interface HTMLSpStockPriceElement extends Components.SpStockPrice, HTMLStencilElement {}
  var HTMLSpStockPriceElement: {
    prototype: HTMLSpStockPriceElement;
    new (): HTMLSpStockPriceElement;
  };

  interface HTMLSpTooltipToggleElement extends Components.SpTooltipToggle, HTMLStencilElement {}
  var HTMLSpTooltipToggleElement: {
    prototype: HTMLSpTooltipToggleElement;
    new (): HTMLSpTooltipToggleElement;
  };
  interface HTMLElementTagNameMap {
    'sp-side-drawer': HTMLSpSideDrawerElement;
    'sp-stock-price': HTMLSpStockPriceElement;
    'sp-tooltip-toggle': HTMLSpTooltipToggleElement;
  }
}

declare namespace LocalJSX {
  interface SpSideDrawer extends JSXBase.HTMLAttributes<HTMLSpSideDrawerElement> {
    'opened'?: boolean;
    'title'?: string;
  }
  interface SpStockPrice extends JSXBase.HTMLAttributes<HTMLSpStockPriceElement> {}
  interface SpTooltipToggle extends JSXBase.HTMLAttributes<HTMLSpTooltipToggleElement> {
    'text'?: string;
  }

  interface IntrinsicElements {
    'sp-side-drawer': SpSideDrawer;
    'sp-stock-price': SpStockPrice;
    'sp-tooltip-toggle': SpTooltipToggle;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


