/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SpSideDrawer {
    'open': () => Promise<void>;
    'opened': boolean;
    'title': string;
  }
}

declare global {


  interface HTMLSpSideDrawerElement extends Components.SpSideDrawer, HTMLStencilElement {}
  var HTMLSpSideDrawerElement: {
    prototype: HTMLSpSideDrawerElement;
    new (): HTMLSpSideDrawerElement;
  };
  interface HTMLElementTagNameMap {
    'sp-side-drawer': HTMLSpSideDrawerElement;
  }
}

declare namespace LocalJSX {
  interface SpSideDrawer extends JSXBase.HTMLAttributes<HTMLSpSideDrawerElement> {
    'opened'?: boolean;
    'title'?: string;
  }

  interface IntrinsicElements {
    'sp-side-drawer': SpSideDrawer;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


